#!/bin/bash
export OS_USERNAME=demo
export OS_PASSWORD=pass
export OS_TENANT_NAME=demo
export OS_REGION_NAME=RegionOne
export OS_AUTH_URL=${OS_AUTH_PROTOCOL:-http}://`juju run --unit  keystone/0 "unit-get private-address"`:5000/v2.0
